

CREATE TABLE IF NOT EXISTS bookmark_books (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  coverart TEXT, 
  description TEXT,
  googleid TEXT NOT NULL
);