CREATE TABLE IF NOT EXISTS bookmark_notes(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  notetitle TEXT NOT NULL,
  notedate TEXT ,
  notecontent TEXT NOT NULL,
  bookinfoid INTEGER REFERENCES bookmark_user_book_info(id) ON DELETE CASCADE NOT NULL 
)